name: Build Android Appbundle

on:
  push:
    branches:
     - main
    paths-ignore:
     - .github/workflows/build_appbundle.yaml
jobs:

  build-android-appbundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get

      - name: Run test
        run: flutter test

      - name: Android Build Appbundle
        run: flutter build appbundle

      - name: Save appbundle to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Appbundle
          path: build/app/outputs/bundle/release/app-release.aab
