name: Dart Formatter

on:
  push:
    branches-ignore:
      - main
      - dev
    paths-ignore:
      - .github/workflows/dart_formatter.yaml

jobs:

  dart-formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Apply analyze fixes
        run: dart fix --apply

      - name: Dart formatting
        run: dart format .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: "chore: Code formatting"
          branch: '${{ github.ref }}'
          token: '${{ secrets.WORKFLOW_CORE_KIT }}'
